### ISSUE TITLE
How to prepare the input file of 'edgelist.csv'.

### ISSUE THREAD

**Issue by Galaxy-228** [KSUNetSE/GeCoNet-Tool#1]
Dear GeCoNet Development Team,
Thanks so much for developing the GeCoNet software.
I would like to inquire about the preparation of the 'edgelist.csv' input file and how to get it. 

Could you provide a simple example file ?

Best wishes,
Jie

**Comment by KSUNetSE** [comment]
Jie,

I think you are not getting the entire window with the start button.
Can you please try to enlarge the interface window? You can do this by dragging out the lower left corner of the window.
Please let me know.

Caterina
________________________________

**Comment by Galaxy-228** [comment]
Caterina,
Thanks so much for your reply.


I have tried to enlarge the interface window by dragging out the lower left corner of the window as you told, but it does not work.
Additionally, When I open the software, the following pop-up window appears.

Thanks for your help again.


Jie












------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "KSUNetSE/GeCoNet-Tool"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月16日(星期五) 凌晨2:29
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [KSUNetSE/GeCoNet-Tool] How to prepare the input file of 'edgelist.csv'. (Issue #1)





 Jie, 
 
 I think you are not getting the entire window with the start button. 
 Can you please try to enlarge the interface window? You can do this by dragging out the lower left corner of the window. 
 Please let me know. 
 
 Caterina 
 ________________________________

**Comment by KSUNetSE** [comment]
I don’t see the pop up window. Can you please send it again?


Sent from my iPhone

On Aug 15, 2024, at 8:10 PM, Jie Liu ***@***.***> wrote:

﻿

This email originated from outside of K-State.


Caterina,
Thanks so much for your reply.


I have tried to enlarge the interface window by dragging out the lower left corner of the window as you told, but it does not work.
Additionally, When I open the software, the following pop-up window appears.

Thanks for your help again.


Jie












------------------&nbsp;原始邮件&nbsp;------------------
发件人: "KSUNetSE/GeCoNet-Tool" ***@***.***&gt;;
发送时间:&nbsp;2024年8月16日(星期五) 凌晨2:29
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [KSUNetSE/GeCoNet-Tool] How to prepare the input file of 'edgelist.csv'. (Issue #1)





Jie,

I think you are not getting the entire window with the start button.
Can you please try to enlarge the interface window? You can do this by dragging out the lower left corner of the window.
Please let me know.

Caterina
________________________________
